filterMsg:
  1: 
    sourceCan: can2
    desCan: can1
    filterId: 
      - 0x10FB01D8
      - 0x10FB03D8
      - 0x10FB0FD8

  2: 
    sourceCan: can1
    desCan: can2

cycleMsg:
  VCU_VehicleSpeed: 
    desCan: can1
    cycleTime: 100
    sendId: 0x10FB0CD8
    sendLength: 8
    sendValue: [0x04, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00]

  VCU_VehicleSpdVId:
    desCan: can1
    cycleTime: 100
    sendId: 0x10FB03D8
    sendLength: 8
    sendValue: [0x04, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00]

ota:
  desCan: can1
  cycleTime: 100
  sendId: 0x10FB0FD8
  status1: 02
  status2: 00
  sendLength: 8
  value1: [0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  value2: [0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

ig: 
    desCan: can1
    sourceCan: can1
    cycleTime: 100
    id1: 0x18F0E34A 
    id2: 0x18FF4D4A
    sendId: 0x10FB01D8
    status1: 04 
    status2: 01 
    sendLength: 8
    value1: [0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    value2: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

url: ":8080"

listen: 
  sourceCan: can2
  id: 0x10FB04D8